# Generated by Django 3.2.12 on 2022-05-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_modules', '0002_alter_questionno_weighted_cough_option2'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionNo_blood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=1000)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
