# Generated by Django 3.2.12 on 2022-05-11 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions_modules', '0003_questionno_blood'),
    ]

    operations = [
        migrations.CreateModel(
            name='cough_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='options_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions_modules.cough_questions')),
            ],
        ),
    ]
